services:
  postgres:
    image: postgres:15
    container_name: postgres
    user: "0"
    environment:
      POSTGRES_USER: kafka
      POSTGRES_PASSWORD: kafka
      POSTGRES_DB: kafka_demo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:

    image: kpradeep/java-full-stack:latest
    platform: linux/amd64
    container_name: java_fsd
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/kafka_demo
      SPRING_DATASOURCE_USERNAME: kafka
      SPRING_DATASOURCE_PASSWORD: kafka
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "9090:9090"
volumes:
  pgdata: