name: Build and Push Docker Compose Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build JAR with Maven
        run: ./mvnw clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: kpradeep
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image from Compose
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: kpradeep/java-full-stack:latest

      # Optionally, if you want to test docker-compose up (without push):
      - name: Test with Docker Compose (optional)
        run: docker compose up -d --build
